# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/Architizer/go-utils
    steps:
      - checkout
      - run:
          name: download dependencies
          command: go get -v github.com/rtt/Go-Solr
      - run:
          name: build packages
          working_directory: /go/src/github.com/Architizer/go-utils
          command: |
            go build -v github.com/Architizer/go-utils/suggestion-terms
      - run:
          name: install packages
          command: |
            go install -v github.com/Architizer/go-utils/suggestion-terms/bin/update_suggestion_terms

  lint:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/Architizer/go-utils
    steps:
      - checkout

      - run:
          name: download dependencies
          command: go get -u golang.org/x/lint/golint

      - run: golint

  test:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/Architizer/go-utils
    steps:
      - checkout

      - run:
          name: download dependencies
          command: |
            go get -v github.com/rtt/Go-Solr
      
      - run: go test github.com/Architizer/go-utils/suggestion-terms
  
  push_suggestion_terms_image:
    docker:
      - image: docker
    working_directory: /go/src/github.com/Architizer/go-utils
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build Docker image
          working_directory: /go/src/github.com/Architizer/go-utils/suggestion-terms
          command: docker build -t architizer/update-suggestion-terms .
      - run:
          name: Login to Dockerhub
          command: echo $HUB_PASSWORD | docker login -u $HUB_USERNAME --password-stdin
      - run:
          name: Push image to Docker hub
          command: docker push architizer/update-suggestion-terms

workflows:
  version: 2
  suggestion_terms:
    jobs:
      - build
      - lint
      - test
      - push_suggestion_terms_image:
          requires:
            - build
            - lint
            - test
          filters:
            branches:
              only: master
